[profile.default]
src = "src"
out = "out"
libs = ["lib"]



# RPC 配置
[rpc_endpoints]
xone_testnet = "https://rpc-testnet.xone.plus"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
